### ISSUE TITLE
Switzerland not found?

### ISSUE THREAD

**Issue by benjazehr** [ebuddj/2019-climate#2]
Hi @teelmo 

I don't plan to use the interactive, so no need to hurry. I just played around with it and realized that if I select Switzerland from the list, the app crashes:

`TypeError: "f.a.sortBy(...)[0] is undefined"`

Kind regards, Angelo

**Comment by teelmo** [comment]
Thanks @angelozehr!

The data is also available for Switzerland (+Norway, Serbia, Iceland and Turkey) but I removed these countries from the implementation to be able to make the comparison with EU28: 
"Sweden makes up 2 percent of total CO2 emissions in EU28."

I've now removed the non-EU28 countries from the dropdown menu.

If you are interested in the Switzerland data it is available in the `media/data.json` file.

Best,
_teemo_
